name: deploy_frontend

on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      uses: actions/checkout@v3
          source_dir: 'frontend/'
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
          sync: 'true'
        # inlineScript: |
        #     az storage blob upload-batch -d $web --account-name azureresume1234 -s *
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "AZResumeCDN" --name "AZresumeCDN" --resource-group "azureresume1234"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()